# fly.toml app configuration file generated for fyp-python on 2025-09-16T13:12:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fyp-python"
primary_region = "ams"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
